services:
  postgres:
    image: postgres:16
    container_name: olist_postgres
    environment:
      POSTGRES_USER: olist
      POSTGRES_PASSWORD: olistpw
      POSTGRES_DB: olist_dw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data_raw:/data_raw:ro

volumes:
  pgdata:
